version: "3.3"
services:
    postgres:
        image: postgres:13
        container_name: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
            POSTGRES_DB: "root"
        volumes:
            - ./postgres/initdb.d:/docker-entrypoint-initdb.d
            - ./postgres/postgres_data:/var/lib/postgresql/data
            - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
        restart: always
    api:
        build: ./api
        container_name: api
        environment:
            DATABASE_URL: "postgres://root:root@postgres:5432/root"
        volumes:
            - ./api:/go/src/app
        depends_on:
            - postgres
    nginx:
        image: nginx:stable
        container_name: nginx
        ports:
            - 80:80
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./frontend/dist:/usr/share/nginx/html/frontend
        depends_on:
            - api
